import io
import csv
from typing import Any, Dict, List
from pydantic import BaseModel
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

from app.schemas.report import SecurityOverviewReport

class ReportExportService:
    @staticmethod
    def _sanitize_csv_cell(value: Any) -> str:
        """Sanitize CSV cells to prevent formula injection"""
        if value is None:
            return ""
        
        str_val = str(value)
        if str_val and str_val[0] in ('=', '+', '-', '@', '\t', '\n'):
            return f"'{str_val}"
            
        return str_val

    @staticmethod
    def generate_csv(data: List[Dict[str, Any]]) -> str:
        """Generate a CSV string from a list of dictionaries"""
        if not data:
            return ""
            
        output = io.StringIO()
        writer = csv.writer(output, quoting=csv.QUOTE_MINIMAL)
        
        # Write headers
        headers = list(data[0].keys())
        writer.writerow(headers)
        
        # Write rows
        for row in data:
            writer.writerow([ReportExportService._sanitize_csv_cell(row.get(h, "")) for h in headers])
            
        return output.getvalue()

    @staticmethod
    def generate_security_overview_pdf(report: SecurityOverviewReport) -> bytes:
        """Generate a PDF for the Security Overview Report"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        elements = []
        
        # Title
        elements.append(Paragraph("SentinelSOC Security Operations Center", styles['Title']))
        elements.append(Spacer(1, 12))
        
        elements.append(Paragraph("Security Overview Report", styles['Heading1']))
        elements.append(Paragraph(f"Generated At: {report.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}", styles['Normal']))
        elements.append(Paragraph(f"Period: {report.from_date.strftime('%Y-%m-%d %H:%M')} to {report.to_date.strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
        elements.append(Spacer(1, 24))
        
        # Executive Summary
        elements.append(Paragraph("Executive Summary", styles['Heading2']))
        sum_text = (
            f"During the selected period, SentinelSOC recorded {report.summary.total_events} security events. "
            f"The platform generated {report.summary.total_alerts} alerts, including {report.summary.critical_alerts} critical alerts. "
            f"{report.summary.open_incidents} incidents remain open. "
        )
        if report.summary.average_alert_risk is not None:
            sum_text += f"The average alert risk score was {int(report.summary.average_alert_risk)}/100. "
            
        elements.append(Paragraph(sum_text, styles['Normal']))
        elements.append(Spacer(1, 24))
        
        # Key Metrics Table
        elements.append(Paragraph("Key Metrics", styles['Heading2']))
        
        data = [
            ['Metric', 'Value'],
            ['Total Events', str(report.summary.total_events)],
            ['Critical Events', str(report.summary.critical_events)],
            ['Active Alerts', str(report.summary.open_alerts)],
            ['Critical Alerts', str(report.summary.critical_alerts)],
            ['Open Incidents', str(report.summary.open_incidents)],
            ['Resolved Incidents', str(report.summary.resolved_incidents)],
            ['Response Success', str(report.summary.successful_response_actions)]
        ]
        
        t = Table(data, colWidths=[200, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        elements.append(t)
        elements.append(Spacer(1, 24))
        
        # Footer
        elements.append(Spacer(1, 36))
        elements.append(Paragraph("Generated by SentinelSOC", styles['Italic']))
        
        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
