"""Add Phase 11 rule columns

Revision ID: 097336582371
Revises: 590632205bc1
Create Date: 2026-09-12 00:26:25.146123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '097336582371'
down_revision: Union[str, None] = '590632205bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_rules', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('detection_rules', sa.Column('mitre_technique', sa.String(length=50), nullable=True))
    op.add_column('detection_rules', sa.Column('pattern', sa.String(length=2000), nullable=True))
    op.add_column('detection_rules', sa.Column('distinct_field', sa.String(length=100), nullable=True))
    op.alter_column('detection_rules', 'threshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detection_rules', 'window_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('detection_rules', 'group_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('detection_rules', 'group_by',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('detection_rules', 'window_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('detection_rules', 'threshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('detection_rules', 'distinct_field')
    op.drop_column('detection_rules', 'pattern')
    op.drop_column('detection_rules', 'mitre_technique')
    op.drop_column('detection_rules', 'category')
    # ### end Alembic commands ###
