"""Add risk scoring fields

Revision ID: 17f0858edea6
Revises: 674b9e9f2beb
Create Date: 2026-09-12 10:09:59.110368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f0858edea6'
down_revision: Union[str, None] = '674b9e9f2beb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('alerts', sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('correlations', sa.Column('risk_score', sa.Integer(), nullable=True))
    op.add_column('correlations', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('correlations', sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('correlations', 'risk_factors')
    op.drop_column('correlations', 'risk_level')
    op.drop_column('correlations', 'risk_score')
    op.drop_column('alerts', 'risk_factors')
    op.drop_column('alerts', 'risk_level')
    # ### end Alembic commands ###
