"""phase 16 incident evidence

Revision ID: 3aa5b8119276
Revises: 7975393f85c6
Create Date: 2026-09-13 00:42:57.851671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa5b8119276'
down_revision: Union[str, None] = '7975393f85c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_evidence',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_evidence_evidence_id'), 'incident_evidence', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_id'), 'incident_evidence', ['id'], unique=False)
    op.create_index(op.f('ix_incident_evidence_incident_id'), 'incident_evidence', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_evidence_incident_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_id'), table_name='incident_evidence')
    op.drop_index(op.f('ix_incident_evidence_evidence_id'), table_name='incident_evidence')
    op.drop_table('incident_evidence')
    # ### end Alembic commands ###
