"""add_response_models

Revision ID: 575772c6e1f7
Revises: d1cb11c00396
Create Date: 2026-09-13 15:13:56.461844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575772c6e1f7'
down_revision: Union[str, None] = 'd1cb11c00396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_response_capabilities',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_response_capabilities_application_id'), 'application_response_capabilities', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_response_capabilities_id'), 'application_response_capabilities', ['id'], unique=False)
    op.create_table('response_policies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('minimum_severity', sa.String(length=50), nullable=True),
    sa.Column('minimum_risk_score', sa.Integer(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_policies_action_type'), 'response_policies', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_policies_application_id'), 'response_policies', ['application_id'], unique=False)
    op.create_index(op.f('ix_response_policies_id'), 'response_policies', ['id'], unique=False)
    op.create_table('response_actions',
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_actions_action_type'), 'response_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_response_actions_alert_id'), 'response_actions', ['alert_id'], unique=False)
    op.create_index(op.f('ix_response_actions_application_id'), 'response_actions', ['application_id'], unique=False)
    op.create_index(op.f('ix_response_actions_id'), 'response_actions', ['id'], unique=False)
    op.create_index(op.f('ix_response_actions_incident_id'), 'response_actions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_response_actions_requested_at'), 'response_actions', ['requested_at'], unique=False)
    op.create_index(op.f('ix_response_actions_requested_by'), 'response_actions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_response_actions_status'), 'response_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_actions_status'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_requested_by'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_requested_at'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_incident_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_application_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_alert_id'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_action_type'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_response_policies_id'), table_name='response_policies')
    op.drop_index(op.f('ix_response_policies_application_id'), table_name='response_policies')
    op.drop_index(op.f('ix_response_policies_action_type'), table_name='response_policies')
    op.drop_table('response_policies')
    op.drop_index(op.f('ix_application_response_capabilities_id'), table_name='application_response_capabilities')
    op.drop_index(op.f('ix_application_response_capabilities_application_id'), table_name='application_response_capabilities')
    op.drop_table('application_response_capabilities')
    # ### end Alembic commands ###
