"""Add MLModel and detection_source

Revision ID: 5f1cbf236e5e
Revises: 3aa5b8119276
Create Date: 2026-09-13 01:14:05.198754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f1cbf236e5e'
down_revision: Union[str, None] = '3aa5b8119276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('feature_version', sa.String(length=50), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('training_window_start', sa.DateTime(), nullable=True),
    sa.Column('training_window_end', sa.DateTime(), nullable=True),
    sa.Column('training_sample_count', sa.Integer(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('baseline_statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_path', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_application_id'), 'ml_models', ['application_id'], unique=False)
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.add_column('alerts', sa.Column('detection_source', sa.String(length=50), nullable=False, server_default='RULE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'detection_source')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_application_id'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
