"""Add correlation models

Revision ID: 674b9e9f2beb
Revises: 097336582371
Create Date: 2026-09-12 10:01:39.964719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '674b9e9f2beb'
down_revision: Union[str, None] = '097336582371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('time_window_seconds', sa.Integer(), nullable=False),
    sa.Column('sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_rules_application_id'), 'correlation_rules', ['application_id'], unique=False)
    op.create_index(op.f('ix_correlation_rules_id'), 'correlation_rules', ['id'], unique=False)
    op.create_table('correlations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('first_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unique_hash', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['correlation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlations_application_id'), 'correlations', ['application_id'], unique=False)
    op.create_index(op.f('ix_correlations_id'), 'correlations', ['id'], unique=False)
    op.create_index(op.f('ix_correlations_unique_hash'), 'correlations', ['unique_hash'], unique=True)
    op.create_table('correlation_events',
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('security_event_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('correlation_id', 'security_event_id')
    )
    op.create_table('correlation_alerts',
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['correlation_id'], ['correlations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('correlation_id', 'alert_id')
    )
    op.add_column('alerts', sa.Column('correlation_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'alerts', 'correlations', ['correlation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'correlation_id')
    op.drop_table('correlation_alerts')
    op.drop_table('correlation_events')
    op.drop_index(op.f('ix_correlations_unique_hash'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_application_id'), table_name='correlations')
    op.drop_table('correlations')
    op.drop_index(op.f('ix_correlation_rules_id'), table_name='correlation_rules')
    op.drop_index(op.f('ix_correlation_rules_application_id'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
