"""phase_15_incident_management

Revision ID: 7975393f85c6
Revises: 8a186f58c769
Create Date: 2026-09-13 00:06:16.413798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7975393f85c6'
down_revision: Union[str, None] = '8a186f58c769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_sequences',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_comments',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.String(length=5000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_comments_id'), 'incident_comments', ['id'], unique=False)
    op.create_index(op.f('ix_incident_comments_incident_id'), 'incident_comments', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_comments_user_id'), 'incident_comments', ['user_id'], unique=False)
    op.create_table('incident_events',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('security_event_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_event_id'], ['security_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'security_event_id')
    )
    op.add_column('incidents', sa.Column('correlation_id', sa.Uuid(), nullable=True))
    op.add_column('incidents', sa.Column('contained_at', sa.DateTime(), nullable=True))
    op.add_column('incidents', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_incidents_correlation_id'), 'incidents', ['correlation_id'], unique=False)
    op.create_foreign_key(None, 'incidents', 'correlations', ['correlation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_correlation_id'), table_name='incidents')
    op.drop_column('incidents', 'closed_at')
    op.drop_column('incidents', 'contained_at')
    op.drop_column('incidents', 'correlation_id')
    op.drop_table('incident_events')
    op.drop_index(op.f('ix_incident_comments_user_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_incident_id'), table_name='incident_comments')
    op.drop_index(op.f('ix_incident_comments_id'), table_name='incident_comments')
    op.drop_table('incident_comments')
    op.drop_table('incident_sequences')
    # ### end Alembic commands ###
