"""add_alert_comments

Revision ID: 8a186f58c769
Revises: 17f0858edea6
Create Date: 2026-09-12 10:25:39.309989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a186f58c769'
down_revision: Union[str, None] = '17f0858edea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_comments',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('comment', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_comments_alert_id'), 'alert_comments', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_comments_id'), 'alert_comments', ['id'], unique=False)
    op.create_index(op.f('ix_alert_comments_user_id'), 'alert_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_comments_user_id'), table_name='alert_comments')
    op.drop_index(op.f('ix_alert_comments_id'), table_name='alert_comments')
    op.drop_index(op.f('ix_alert_comments_alert_id'), table_name='alert_comments')
    op.drop_table('alert_comments')
    # ### end Alembic commands ###
