"""Add ThreatIntel models

Revision ID: d1cb11c00396
Revises: 5f1cbf236e5e
Create Date: 2026-09-13 01:35:30.219350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cb11c00396'
down_revision: Union[str, None] = '5f1cbf236e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intel_cache',
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'indicator_type', 'provider', name='uix_ti_cache_indicator_provider')
    )
    op.create_index(op.f('ix_threat_intel_cache_expires_at'), 'threat_intel_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_threat_intel_cache_id'), 'threat_intel_cache', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intel_cache_indicator'), 'threat_intel_cache', ['indicator'], unique=False)
    op.create_index(op.f('ix_threat_intel_cache_indicator_type'), 'threat_intel_cache', ['indicator_type'], unique=False)
    op.create_table('threat_intel_indicators',
    sa.Column('indicator', sa.String(), nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('malicious', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('reputation', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_intel_indicators_confidence'), 'threat_intel_indicators', ['confidence'], unique=False)
    op.create_index(op.f('ix_threat_intel_indicators_id'), 'threat_intel_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_threat_intel_indicators_indicator'), 'threat_intel_indicators', ['indicator'], unique=False)
    op.create_index(op.f('ix_threat_intel_indicators_indicator_type'), 'threat_intel_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_threat_intel_indicators_malicious'), 'threat_intel_indicators', ['malicious'], unique=False)
    op.create_table('alert_threat_intel',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('threat_intel_indicator_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_intel_indicator_id'], ['threat_intel_indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'threat_intel_indicator_id', name='uix_alert_ti_indicator')
    )
    op.create_index(op.f('ix_alert_threat_intel_alert_id'), 'alert_threat_intel', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_threat_intel_id'), 'alert_threat_intel', ['id'], unique=False)
    op.create_index(op.f('ix_alert_threat_intel_threat_intel_indicator_id'), 'alert_threat_intel', ['threat_intel_indicator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_threat_intel_threat_intel_indicator_id'), table_name='alert_threat_intel')
    op.drop_index(op.f('ix_alert_threat_intel_id'), table_name='alert_threat_intel')
    op.drop_index(op.f('ix_alert_threat_intel_alert_id'), table_name='alert_threat_intel')
    op.drop_table('alert_threat_intel')
    op.drop_index(op.f('ix_threat_intel_indicators_malicious'), table_name='threat_intel_indicators')
    op.drop_index(op.f('ix_threat_intel_indicators_indicator_type'), table_name='threat_intel_indicators')
    op.drop_index(op.f('ix_threat_intel_indicators_indicator'), table_name='threat_intel_indicators')
    op.drop_index(op.f('ix_threat_intel_indicators_id'), table_name='threat_intel_indicators')
    op.drop_index(op.f('ix_threat_intel_indicators_confidence'), table_name='threat_intel_indicators')
    op.drop_table('threat_intel_indicators')
    op.drop_index(op.f('ix_threat_intel_cache_indicator_type'), table_name='threat_intel_cache')
    op.drop_index(op.f('ix_threat_intel_cache_indicator'), table_name='threat_intel_cache')
    op.drop_index(op.f('ix_threat_intel_cache_id'), table_name='threat_intel_cache')
    op.drop_index(op.f('ix_threat_intel_cache_expires_at'), table_name='threat_intel_cache')
    op.drop_table('threat_intel_cache')
    # ### end Alembic commands ###
