"""Add DetectionRule model

Revision ID: decf4b8fbc3b
Revises: e63b59cf2fea
Create Date: 2026-09-11 20:46:14.893953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decf4b8fbc3b'
down_revision: Union[str, None] = 'e63b59cf2fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('group_by', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_application_id'), 'detection_rules', ['application_id'], unique=False)
    op.create_index(op.f('ix_detection_rules_event_type'), 'detection_rules', ['event_type'], unique=False)
    op.create_index(op.f('ix_detection_rules_id'), 'detection_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_rules_id'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_event_type'), table_name='detection_rules')
    op.drop_index(op.f('ix_detection_rules_application_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
