"""Add indexes for Event Explorer

Revision ID: e63b59cf2fea
Revises: edc26d40b382
Create Date: 2026-09-11 18:44:44.340956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63b59cf2fea'
down_revision: Union[str, None] = 'edc26d40b382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_security_events_session_id'), 'security_events', ['session_id'], unique=False)
    op.create_index('ix_security_events_sev_timestamp', 'security_events', ['severity', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_events_user_id'), 'security_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_events_user_id'), table_name='security_events')
    op.drop_index('ix_security_events_sev_timestamp', table_name='security_events')
    op.drop_index(op.f('ix_security_events_session_id'), table_name='security_events')
    # ### end Alembic commands ###
