"""Add application API keys

Revision ID: edc26d40b382
Revises: 5e33a03d64d3
Create Date: 2026-09-11 01:33:11.107616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc26d40b382'
down_revision: Union[str, None] = '5e33a03d64d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_api_keys',
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_api_keys_application_id'), 'application_api_keys', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_api_keys_expires_at'), 'application_api_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_application_api_keys_id'), 'application_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_application_api_keys_is_active'), 'application_api_keys', ['is_active'], unique=False)
    op.create_index(op.f('ix_application_api_keys_key_prefix'), 'application_api_keys', ['key_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_api_keys_key_prefix'), table_name='application_api_keys')
    op.drop_index(op.f('ix_application_api_keys_is_active'), table_name='application_api_keys')
    op.drop_index(op.f('ix_application_api_keys_id'), table_name='application_api_keys')
    op.drop_index(op.f('ix_application_api_keys_expires_at'), table_name='application_api_keys')
    op.drop_index(op.f('ix_application_api_keys_application_id'), table_name='application_api_keys')
    op.drop_table('application_api_keys')
    # ### end Alembic commands ###
